declare module "balm-ui-plus"
declare module "balm-ui/components/radio"
declare module "balm-ui/components/checkbox"
declare module "balm-ui/components/switch"
declare module "balm-ui/components/collapse"
declare module "balm-ui/directives/ripple"
declare module "balm-ui/plugins/theme"
